pipeline {
    agent any
    tools {
      maven "M3"
      jdk "JDK11"
    }
  
  stages {
    stage('Git fatch') {
      
      steps {
        echo 'Git fatch'
        git url: 'https://github.com/SooYong-Jeong/spring-petclinic.git', 
          branch: 'main', credentialsId: 'gitCredential'
      }
    }
      stage('Maven build') {
      
      steps {
        echo 'Maven build'
        sh 'mvn -Dmaven.test.failure.ignore-true clean package'
      }
    }
      stage('Docker image') {
      
      steps {
        echo 'Docker image'
      }
    }
      stage('Image push') {
      
      steps {
        echo 'Image push'
      }
    }
      stage('Codedeploy') {
      
      steps {
        echo 'Codedeploy'
      }
    }
  }
}
