pipeline {
    agent any
    tools {
        maven 'M3'
        jdk 'JDK11'
    }   

    environment {
        AWS_ACCOUNT_ID="257307634175"
        AWS_CREDENTIAL_NAME = "awsEcrCredentials"
        REGION = "ap-northeast-2"
        DOCKER_IMAGE_NAME="project04-spring-petclinic"
        DOCKER_TAG="1.0"
        ECR_REPOSITORY = "${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-2.amazonaws.com"
        ECR_DOCKER_IMAGE = "${ECR_REPOSITORY}/${DOCKER_IMAGE_NAME}"
        ECR_DOCKER_TAG = "${DOCKER_TAG}"
    }

    stages {
        stage('Git clone') {
            steps {
                git url: 'https://github.com/SooYong-Jeong/spring-petclinic.git/',
                    branch: 'main', credentialsId: 'gitCredential'
            }
            post {
                success {
                    echo 'success clone project'
                }
                failure {
                    error 'fail clone project' // exit pipeline
                }
            }
        }
        
        stage ('mvn Build') {
            steps {
                sh 'mvn -Dmaven.test.failure.ignore=true install' 
            }
            post {
                success {
                    junit 'target/surefire-reports/**/*.xml' 
                }
            }
        }
        
        stage ('Docker Build') {
            steps {
                dir("${env.WORKSPACE}") {
                    sh 'docker build -t ${ECR_DOCKER_IMAGE}:${ECR_DOCKER_TAG} .'
                }
            }
            
            post {
                success {
                    echo "Docker build success!"
                }
            }
        }       

        stage('Push Docker Image') {
            steps {
                echo "Push Docker Image to ECR"
                script{
                    // cleanup current user docker credentials
                    sh 'rm -f ~/.dockercfg ~/.docker/config.json || true'                    
                   
                    docker.withRegistry("https://${ECR_REPOSITORY}", "ecr:${REGION}:${AWS_CREDENTIAL_NAME}") {
                      docker.image("${ECR_DOCKER_IMAGE}:${ECR_DOCKER_TAG}").push()
                    }
                }
            }
            post {
                success {
                    echo "Push Docker Image success!"
                }
            }
        }
        stage('Upload to S3') {
            steps {
                echo "Upload to S3"
                sh 'zip -r deploy-1.0.zip ./deploy appspec.yml'
                sh 'aws s3 cp --region ap-northeast-2 --acl private ./deploy-1.0.zip s3://project04-codedeploy'
                sh 'rm -rf ./deploy-1.0.zip'
            }
        }
                
       stage('Codedeploy Workload') {
            steps {
                echo "Codedeploy Workload"   
                sh '''
                    aws deploy create-deployment --application-name project04 \
                    --deployment-config-name CodeDeployDefault.OneAtATime \
                    --deployment-group-name project04-deploy \
                    --s3-location bucket=project04-codedeploy,bundleType=zip,key=deploy-1.0.zip
                    '''
            }
        }
    }
}
